[images]
  remote_images = ["https://same-assets.com/*"]

[build]
  command = "bun install && bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_USE_PACKAGE_LOCK = "false"
  NEXT_USE_BUN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
