import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Code, CheckCircle, ShieldCheck, AlertTriangle } from "lucide-react"

export default function ResponseSampleCodePage() {
  return (
    <div className="container space-y-6 py-8">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight">Response Example</h1>
        <p className="text-lg text-muted-foreground">
          Sample response payloads from EcobankPay API endpoints
        </p>
      </div>

      <Alert>
        <ShieldCheck className="h-4 w-4" />
        <AlertTitle>Important Note</AlertTitle>
        <AlertDescription>
          Always validate the response signature using the HMAC SHA-256 algorithm and your merchant secret key before processing any transaction.
        </AlertDescription>
      </Alert>

      <Tabs defaultValue="successful" className="w-full">
        <TabsList className="grid w-full md:w-auto grid-cols-3">
          <TabsTrigger value="successful">Successful Response</TabsTrigger>
          <TabsTrigger value="failed">Failed Response</TabsTrigger>
          <TabsTrigger value="callback">Callback Response</TabsTrigger>
        </TabsList>
        <TabsContent value="successful" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-green-500" />
                Successful Payment Response
              </CardTitle>
              <CardDescription>
                This is a sample response for a successful payment transaction
              </CardDescription>
            </CardHeader>
            <CardContent>
              <pre className="bg-muted p-4 rounded-md overflow-auto text-sm">
{`{
  "status": "success",
  "code": "00",
  "message": "Transaction successful",
  "data": {
    "transactionId": "ECOBANK123456789",
    "merchantReference": "ORDER-12345",
    "amount": "100.00",
    "currency": "GHS",
    "paymentMethod": "mobile_money",
    "provider": "mtn",
    "customerPhone": "233244000000",
    "customerEmail": "customer@example.com",
    "transactionDate": "2025-03-28T10:35:42.000Z",
    "paymentStatus": "COMPLETED",
    "receiptNumber": "ECO78912345"
  },
  "signature": "c7b7f9a53f959d83fa03c44c2f7be4b8ccc8063cc38bdc7fc0f753d6a9cb5812"
}`}
              </pre>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Response Parameters</CardTitle>
              <CardDescription>
                Details of each field in the successful response
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Parameter</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Description</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="font-medium">status</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>The status of the transaction, values can be "success", "pending", or "failed"</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">code</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Response code, "00" for successful transactions</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">message</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Human-readable description of the response</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.transactionId</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Unique identifier generated by EcobankPay for the transaction</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.merchantReference</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Your original order reference submitted in the request</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.amount</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>The transaction amount</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.currency</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Three-letter ISO currency code</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.paymentMethod</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>The payment method used (card, mobile_money, bank_transfer)</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">data.paymentStatus</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>Current status of the payment (COMPLETED, PENDING, FAILED)</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">signature</TableCell>
                    <TableCell>String</TableCell>
                    <TableCell>HMAC SHA-256 signature of the response for verification</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="failed" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-red-500" />
                Failed Payment Response
              </CardTitle>
              <CardDescription>
                This is a sample response for a failed payment transaction
              </CardDescription>
            </CardHeader>
            <CardContent>
              <pre className="bg-muted p-4 rounded-md overflow-auto text-sm">
{`{
  "status": "failed",
  "code": "E001",
  "message": "Insufficient funds in customer account",
  "data": {
    "transactionId": "ECOBANK987654321",
    "merchantReference": "ORDER-67890",
    "amount": "500.00",
    "currency": "GHS",
    "paymentMethod": "mobile_money",
    "provider": "mtn",
    "customerPhone": "233244111111",
    "transactionDate": "2025-03-28T10:40:15.000Z",
    "paymentStatus": "FAILED",
    "errorDetail": "Customer has insufficient balance to complete this transaction"
  },
  "signature": "d8e6f7a92c959c72eb14d33d1e6be3a7bdd7154bb27bde5ea1e642c5a8db4721"
}`}
              </pre>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="callback" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Code className="h-5 w-5" />
                Callback Notification Payload
              </CardTitle>
              <CardDescription>
                Sample webhook notification sent to your callback URL
              </CardDescription>
            </CardHeader>
            <CardContent>
              <pre className="bg-muted p-4 rounded-md overflow-auto text-sm">
{`{
  "event": "payment.completed",
  "data": {
    "transactionId": "ECOBANK123456789",
    "merchantReference": "ORDER-12345",
    "amount": "100.00",
    "currency": "GHS",
    "paymentMethod": "mobile_money",
    "provider": "mtn",
    "customerPhone": "233244000000",
    "customerEmail": "customer@example.com",
    "transactionDate": "2025-03-28T10:35:42.000Z",
    "paymentStatus": "COMPLETED",
    "receiptNumber": "ECO78912345"
  },
  "timestamp": "2025-03-28T10:35:45.000Z",
  "signature": "a9c7f8b52e848c72fa13c33c1f5ad4a6acc7053bb36ade4ea0f532c4a7cb4710"
}`}
              </pre>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
